name: 6.1.141 欧加真OKI内核快速构建(精简版)

env:
  TZ: Asia/Shanghai
  ANDROID_VERSION: 'android14'
  KERNEL_VERSION: '6.1'
  SUB_VERSION: '141'
  KERNEL_NAME: 'android14-11-o-gca13bffobf09'
  CCACHE_KEY: ccache-ecsv3-6.1.141-droidspaces

on:
  workflow_dispatch:
    inputs:
      ccache_update:
        description: '更新ccache缓存(将本次编译生成的ccache缓存覆盖至仓库缓存)'
        required: true
        type: boolean
        default: false
      kernel_suffix:
        description: '内核后缀(留空默认,开头别加连字符)'
        required: false
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: 安装环境依赖+初始化源码仓库及llvm-Clang20工具链
        run: |
          rm -rf kernel_workspace
          mkdir kernel_workspace
          cd kernel_workspace
          
          sudo apt-mark hold firefox && sudo apt-mark hold libc-bin
          sudo apt purge man-db && sudo rm -rf /var/lib/man-db/auto-update
          sudo apt update && sudo apt-get install -y --no-install-recommends binutils python-is-python3 libssl-dev libelf-dev &
          
          # 使用特化优化内核编译缓存的 ccache-ECS
          wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/lib/ccache-x86-64 -O ccache 
          sudo cp -f ./ccache /usr/bin/ccache && sudo chmod +x /usr/bin/ccache && rm -f ./ccache &
          
          echo "正在克隆源码仓库..."
          aria2c -s16 -x16 -k1M https://github.com/cctv18/android_kernel_common_oneplus_sm8650/archive/refs/heads/oneplus/sm8650_b_16.0.0_oneplus12_6.1.141.zip -o common.zip 
          unzip -q common.zip && mv "android_kernel_common_oneplus_sm8650-oneplus-sm8650_b_16.0.0_oneplus12_6.1.141" common && rm -rf common.zip &
          
          echo "正在克隆llvm-Clang20工具链..." 
          mkdir -p clang20 
          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang20-r547379/clang-r547379.zip -o clang.zip 
          unzip -q clang.zip -d clang20 && rm -rf clang.zip &
          
          echo "正在克隆构建工具..." 
          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang20-r547379/build-tools.zip -o build-tools.zip 
          unzip -q build-tools.zip && rm -rf build-tools.zip &
          
          wait
          echo "所有源码及llvm-Clang20工具链初始化完成！"
          
          echo "正在去除 ABI 保护 & 去除 dirty 后缀..."
          rm common/android/abi_gki_protected_exports_* || true
          for f in common/scripts/setlocalversion; do
            sed -i 's/ -dirty//g' "$f"
            sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' "$f"
          done

      - name: 应用内存访问修复补丁
        run: |
          echo "正在应用来自 GitHub 的内存访问修复补丁..."
          cd kernel_workspace/common
          curl -sSL https://github.com/Andy312432/android_kernel_samsung_sm8650_gunyah/commit/3d8767092fa186b77dfcbc5fd14b53ae17b04bb2.patch | git am
          echo "补丁应用完成。"

      - name: 配置ccache目录
        run: |
          echo "CCACHE_DIR=$HOME/.ccache_${{ env.KERNEL_VERSION }}.${{ env.SUB_VERSION }}" >> $GITHUB_ENV
          echo "CCACHE_MAXSIZE=3G" >> $GITHUB_ENV
          echo "CCACHE_REAL_KEY=${{ env.CCACHE_KEY }}-${{ runner.os }}-${{ github.ref_name }}" >> $GITHUB_ENV

      - name: 载入当前版本内核的 ccache缓存
        uses: actions/cache@v5
        id: ccache-restore
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ env.CCACHE_REAL_KEY }}
          restore-keys: |
            ${{ env.CCACHE_KEY }}-${{ runner.os }}-

      - name: 拉取公共预置 ccache 缓存
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -d "${{ env.CCACHE_DIR }}" ] && [ "$(ls -A ${{ env.CCACHE_DIR }} 2>/dev/null)" ]; then
            echo "检测到本地已成功载入 ccache 缓存，跳过公共 ccache 拉取！"
            exit 0
          fi
          mkdir -p ${{ env.CCACHE_DIR }}
          FILE_NAME="ccache-${{ env.KERNEL_VERSION }}.${{ env.SUB_VERSION }}-Droidspaces.tar.zst"
          if gh release download -p "$FILE_NAME" -R cctv18/public_ccache; then
            tar -I zstd -xf "$FILE_NAME" -C ${{ env.CCACHE_DIR }}
          else
            echo "公共 ccache 中未找到对应文件，将进行全量全新编译..."
          fi

      - name: 清除旧 ccache 缓存
        if: inputs.ccache_update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache delete ${{ env.CCACHE_REAL_KEY }} -R ${{ github.repository }} || echo "旧缓存不存在或已被清理"

      - name: 初始化并配置ccache
        run: |
          export CCACHE_COMPILERCHECK="none"
          export CCACHE_BASEDIR="${{ github.workspace }}"
          export CCACHE_NOHASHDIR="true"
          export CCACHE_DIR="${{ env.CCACHE_DIR }}"
          export CCACHE_MAXSIZE="${{ env.CCACHE_MAXSIZE }}"
          mkdir -p "$CCACHE_DIR"
          ccache -M "$CCACHE_MAXSIZE"
          ccache -o compression=true
          ccache -s

      - name: 添加 ReSukiSU & KPM
        run: |
          cd kernel_workspace
          echo "正在配置 ReSukiSU..."
          curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/refs/heads/main/kernel/setup.sh" | bash -s main
          echo 'CONFIG_KSU_FULL_NAME_FORMAT="%TAG_NAME%-%COMMIT_SHA%@cctv18"' >> ./common/arch/arm64/configs/gki_defconfig
          
          echo "正在配置 KPM (KpatchNext)..."
          cd ./KernelSU
          curl -LSs "https://raw.githubusercontent.com/pershoot/KPatch-Next/dev-susfs/kpm/setup.sh" | bash -s dev-susfs

      - name: 应用 LZ4 1.10.0 & ZSTD 1.5.7 补丁
        run: |
          cd kernel_workspace
          git clone --depth=1 https://github.com/$GITHUB_REPOSITORY.git -b $GITHUB_REF_NAME patch_repo
          cp ./patch_repo/zram_patch/001-lz4.patch ./common/
          cp ./patch_repo/zram_patch/lz4armv8.S ./common/lib
          cp ./patch_repo/zram_patch/002-zstd.patch ./common/
          cd ./common
          git apply -p1 < 001-lz4.patch || true
          patch -p1 < 002-zstd.patch || true

      - name: 写入内核配置项
        run: |
          cd kernel_workspace/common
          CONFIG_FILE="./arch/arm64/configs/gki_defconfig"
          
          # Droidspaces Standard (容器 + ntsync)
          echo "CONFIG_DROIDSPACES=y" >> $CONFIG_FILE
          echo "CONFIG_DROIDSPACES_NTSYNC=y" >> $CONFIG_FILE
          
          # 网络功能拓展配置
          echo "CONFIG_NETFILTER_ADVANCED=y" >> $CONFIG_FILE
          echo "CONFIG_IP_SET=y" >> $CONFIG_FILE
          echo "CONFIG_IP_SET_HASH_IP=y" >> $CONFIG_FILE
          echo "CONFIG_NETFILTER_XTABLES=y" >> $CONFIG_FILE
          
          # 三星 SSG IO 调度器
          echo "CONFIG_MQ_IOSCHED_SSG=y" >> $CONFIG_FILE
          echo "CONFIG_DEFAULT_MQ_IOSCHED_SSG=y" >> $CONFIG_FILE
          
          # 内核级基带保护
          echo "CONFIG_BASEBAND_GUARD=y" >> $CONFIG_FILE

      - name: 编译内核
        run: |
          cd kernel_workspace/common
          export PATH="$PWD/../clang20/bin:$PWD/../build-tools/bin:$PATH"
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CLANG_TRIPLE=aarch64-linux-gnu-
          
          make O=out LLVM=1 gki_defconfig
          make O=out LLVM=1 -j$(nproc)
          
          # 处理内核后缀
          if [ -n "${{ github.event.inputs.kernel_suffix }}" ]; then
            mv out/arch/arm64/boot/Image out/arch/arm64/boot/Image-${{ github.event.inputs.kernel_suffix }}
          fi

      - name: 上传内核产物
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Image-${{ github.run_id }}
          path: kernel_workspace/common/out/arch/arm64/boot/Image*
